---
title: "biggest_component_changes"
output: html_document
date: '2022-06-30'
---

#showing histogram cc and changes of the same movie

```{r}


library(openxlsx)
library(stringr)
library(dplyr)
library(reshape2)
library(igraph)
library(R.matlab)






f <- function(x) {
    if(is.list(x)) lapply(x, f)
    else ifelse(length(x) == 0, 0, x)
}




length_of_movie<-54000
#how many frame in a batch
number_of_frame<-1

#seq by the  number of frames
numbers<-seq(1, length_of_movie, by=number_of_frame)
with_Angelsub<-TRUE


#if i want without angelsub for calcualtin of interaction choose Allinteraction.mat
#if you do want it choose AllinteractionWithAngelsub.mat

if(length_of_movie == 54000){
    name_of_interactionmat_len<-"interactionMatrix_frame_0_to_54000_gap_120_interaction_length.txt"
  name_of_interactionmat_num<-"interactionMatrix_frame_0_to_54000_gap_120_interaction_number.txt"
}
if(length_of_movie == 27000){
  name_of_interactionmat_len<-"interactionMatrix_frame_0_to_27000_gap_120_interaction_length.txt"
  name_of_interactionmat_num<-"interactionMatrix_frame_0_to_27000_gap_120_interaction_number.txt"
}


if(with_Angelsub == TRUE){
  
  name_of_mat<-"AllinteractionWithAngelsub.mat"
}else{
  name_of_mat<-"Allinteraction.mat"
}
dir<-list.dirs(recursive = F,path = "D:/Mated_Rejected_Naive_oneMovieEach/_Rejected")
num_of_movie=1

filepath<-paste0(dir[num_of_movie], '/',name_of_mat)
if(!(file.exists(filepath))){
  stop("Allinteraction.mat does not exist!!!please creat it with MainInteractionAllAngelSub.m ")
}

  mat <- (readMat(paste0(dir[num_of_movie], '/',name_of_mat)))
number_of_flys<-sqrt(length(mat[["new.interactionFrameMatrix"]]))
# read each MAT file
  sub_list_mat<-matrix(mat[["new.interactionFrameMatrix"]],nrow = number_of_flys, ncol = number_of_flys)
  df_mat<-as.data.frame(sub_list_mat)
  

    for(i in 1:ncol(df_mat)){
    for(j in 1:nrow(df_mat)){
      if(length(unlist(df_mat[i,j])) == 0){
        df_mat[i,j] <- lapply(df_mat[i,j], function(x)x[lengths(x) == 0] <- 0)
      }
    }
  }
  
  df_mat<-na.omit(df_mat)

  

  #10 flys
  
  
  colnames(df_mat)<-c(1:number_of_flys)
  rownames(df_mat)<-c(1:number_of_flys)
  
  
  all<-data.frame()
  path_to_sub_Scripts<-"C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/code/interactions_network/dynamic/sub_scripts"
  
   setwd(path_to_sub_Scripts)
    files.sources = list.files()
    sapply(files.sources, source)

  all<-all_frames_interaction_above(number_of_flys,sub_list_mat,df_mat)

  #for the acasct every interaction mean 1 
  all<-cbind(all,1)


  library(dplyr)
  library(igraph)
  
  previous_net<-creat_network(all,1,numbers)

  all_changes<-NULL
for(i in 2:(length(numbers)-1)){
  
  current_net<-creat_network(all,i,numbers)
  
  
  #check who really have bigger than 3 cc
  sub_prev_net<-biggest_cc_subgraph(previous_net)
  if(sub_prev_net[[2]] == FALSE){
    # no sub cluster bigger than 3
    sub_prev_net<-(sub_prev_net[[1]])
    size_of_biggest_cc = 0
  }else{
    sub_prev_net<-(sub_prev_net[[1]])
    size_of_biggest_cc= length(sub_prev_net)
  }
  
  
  
  sub_current_net<-biggest_cc_subgraph(current_net)
    if(sub_current_net[[2]] == FALSE){
    # no sub cluster bigger than 3
    sub_current_net<-(sub_current_net[[1]])
    size_of_biggest_cc_current = 0
  }else{
    sub_current_net<-(sub_current_net[[1]])
    size_of_biggest_cc_current= length(sub_current_net)
  }
  
  #if there is a component that is bigger than 3 nodes,the if is inside biggest_cc_subgraph script
  #the biggest cc is 3 but the chnages is 2 and not 3 because if added the

  #only if there is cc that is bigger than 3
 #if(size_of_biggest_cc_current>=3){
    

#if the edges is in one of them 
  changes_in_edges <- length(E(difference(sub_prev_net,sub_current_net)))+length(E(difference(sub_current_net,sub_prev_net)))
  #bigeest cc show the cc if it is bigger than 3,else it is 0
  tmp<-data.frame(change = changes_in_edges,frame = i,size_cc = size_of_biggest_cc_current)
  all_changes<-rbind(all_changes,tmp)
  print(i)
previous_net<-current_net
}  

  
  
  library(ggplot2)
library(reshape2)



# melt the data to a long format
all_changes_melted <- melt(data = all_changes, id.vars = "frame")

library(ggplot2)


cc_and_change<-ggplot(all_changes_melted, aes(frame,value,colour = variable)) + 
  geom_point() + 
  geom_line() +
  facet_wrap(~variable,nrow =2)




#histogram
#length
filepath<-paste0(dir[num_of_movie],"/",name_of_interactionmat_len)
if(!(file.exists(filepath))){
  warning("length interaction matrix does not exist!!!please creat it")
}
filename<-basename(filepath)
mat <- scan(toString(filepath))
numCol <- sqrt(length(mat))
mat <- matrix(mat, ncol = numCol, byrow = TRUE)
rownames(mat)<-1:numCol

sapply(c("dplyr", "ggplot2"), require, character.only = T)

#  convert from matrix to data frame and preserve row names as column
mat <- data.frame(fly = row.names(mat), as.data.frame(mat), row.names = NULL)
library(tidyr)
colnames(mat)<-c("fly",1:numCol)
# gather so in a tidy format for ease of use in ggplot2
mat <- gather(as.data.frame(mat), lambda, value, -1)
#mat$fly<-as.numeric(mat$fly)
# plot 1 as described in question
#ggplot(mat, aes(x = fly, y = value)) + geom_histogram(aes(fill = lambda), stat = "identity", position = "dodge")        

# plot 2 using facets to separate as an alternative
length_plot<-ggplot(mat, aes(x = fly, y = value)) + geom_histogram(stat = "identity") + facet_grid(. ~ lambda)+ggtitle(filename)



#number
filepath<-paste0(dir[num_of_movie],"/",name_of_interactionmat_num)

if(!(file.exists(filepath))){
  warning("number interaction matrix does not exist!!!please creat it")
}
filename<-basename(filepath)
mat <- scan(toString(filepath))
numCol <- sqrt(length(mat))
mat <- matrix(mat, ncol = numCol, byrow = TRUE)

rownames(mat)<-1:numCol

sapply(c("dplyr", "ggplot2"), require, character.only = T)

#  convert from matrix to data frame and preserve row names as column
mat <- data.frame(fly = row.names(mat), as.data.frame(mat), row.names = NULL)
library(tidyr)
colnames(mat)<-c("fly",1:numCol)
# gather so in a tidy format for ease of use in ggplot2
mat <- gather(as.data.frame(mat), lambda, value, -1)
#mat$fly<-as.numeric(mat$fly)
# plot 1 as described in question
#ggplot(mat, aes(x = fly, y = value)) + geom_histogram(aes(fill = lambda), stat = "identity", position = "dodge")        

# plot 2 using facets to separate as an alternative
number_plot<-ggplot(mat, aes(x = fly, y = value)) + geom_histogram(stat = "identity") + facet_grid(. ~ lambda)+ggtitle(filename)


plot(number_plot)
plot(length_plot)
plot(cc_and_change)

```






#heatmap instead histogram
```{r}


#dir<-list.dirs(recursive = F,path = "D:/allGroups/Females_Grouped")
#num_of_movie=19

flynames<-c("fly1","fly2","fly3","fly4","fly5","fly6","fly7","fly8","fly9","fly10")

#histogram
#length
filepath<-paste0(dir[num_of_movie],"/",name_of_interactionmat_len)
if(!(file.exists(filepath))){
  warning("length interaction matrix does not exist!!!please creat it")
}

group_name<-basename(dirname(dirname(filepath)))
filename<-basename(filepath)
mat <- scan(toString(filepath))
numCol <- sqrt(length(mat))
mat <- matrix(mat, ncol = numCol, byrow = TRUE)

rownames(mat)<-flynames
colnames(mat)<-flynames


#mat<-as.data.frame(mat)
library(tidyverse)
mat[upper.tri(mat)]=NA

library(reshape2)
library(dplyr)
library(tidyverse)


melted_mat <- melt(mat, na.rm = TRUE)

melted_mat$value<-as.numeric(format(round(melted_mat$value, 3), nsmall = 2))

#dt2 <- mat %>%
 # rownames_to_column() %>%
  #gather(colname, value, -rowname, na.rm = T)
#head(dt2)





library(ggplot2)
ggheatmap <-ggplot(data = melted_mat, aes(Var1, Var2, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "white", high = "red", 
   midpoint = 0.25, limit = c(0,1), space = "Lab", 
   paste0(group_name," LOI")) +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()

length_of_interaction<-ggheatmap + 
geom_text(aes(Var1,Var2 , label = value), color = "black", size = 2) +
theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.grid.major = element_blank(),
  panel.border = element_blank(),
  panel.background = element_blank(),
  axis.ticks = element_blank(),
  legend.justification = c(1, 0),
  legend.position = c(0.6, 0.7),
  legend.direction = "horizontal")+
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                title.position = "top", title.hjust = 0.5))


#library("scales")
#vec_range4 <- rescale(dt2, to = c(0, 5))                # Scale to 0/5
#library(ggplot2)
#ggplot(dt2, aes(x = rowname, y = colname, fill = value)) +
  #geom_tile(color = "black") +
   #scale_fill_gradient(low = "white", high = "blue") +
  #coord_fixed()








#number
filepath<-paste0(dir[num_of_movie],"/",name_of_interactionmat_num)

if(!(file.exists(filepath))){
  warning("number interaction matrix does not exist!!!please creat it")
}
filename<-basename(filepath)
mat <- scan(toString(filepath))
numCol <- sqrt(length(mat))
mat <- matrix(mat, ncol = numCol, byrow = TRUE)

rownames(mat)<-flynames
colnames(mat)<-flynames


#mat<-as.data.frame(mat)
library(tidyverse)
mat[upper.tri(mat)]=NA

library(reshape2)
library(dplyr)
library(tidyverse)


melted_mat <- melt(mat, na.rm = TRUE)

melted_mat$value<-as.numeric(format(round(melted_mat$value, 3), nsmall = 2))



library(ggplot2)
ggheatmap_number <-ggplot(data = melted_mat, aes(Var1, Var2, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "white", high = "blue", 
    space = "Lab", 
   name=paste0(group_name," NOI")) +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()

number_of_interaction<-ggheatmap_number + 
geom_text(aes(Var1,Var2 , label = value), color = "black", size = 2) +
theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.grid.major = element_blank(),
  panel.border = element_blank(),
  panel.background = element_blank(),
  axis.ticks = element_blank(),
  legend.justification = c(1, 0),
  legend.position = c(0.6, 0.7),
  legend.direction = "horizontal")+
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                title.position = "top", title.hjust = 0.5))



plot(length_of_interaction)
plot(number_of_interaction)
```

