---
title: "corrleaction_for_degree"
output: html_document
date: '2022-06-13'
---




correlaction all groupes
```{r}
library(stringr)
library(corrplot)

without_ncloseflys=FALSE
list_of_all_groups_top<-list.dirs(path = "D:/allGroups", full.names = TRUE, recursive = FALSE)

for (index_group in 1:length(list_of_all_groups_top)){
  path_to_group =list_of_all_groups_top[index_group]
  print(path_to_group)
  setwd(path_to_group)
  
  list_of_all_groups<-list.dirs(path = path_to_group, full.names = TRUE, recursive = FALSE)
  degree_corr<-NULL
  
  
  
  
  #orgenizing all the features and degree together and corrleaction
#list of all groupes is the movies
for(i in 1:length(list_of_all_groups)){
  #reading the csv files with paramters
   if(!file.exists(paste0(list_of_all_groups[i], '/','all_frames_degree_new.csv'))){
     warning(paste0(list_of_all_groups[i],"all frames degree dont exist"))
   }else{
     degree_csv<-read.csv(paste0(list_of_all_groups[i], '/','all_frames_degree_new.csv'))
   }
  
    if(!file.exists(paste0(list_of_all_groups[i], '/','per_framefeatures_sum_allflies.csv'))){
     warning(paste0(list_of_all_groups[i],"per frame features dont exist"))
   }else{
     all_features<-read.csv(paste0(list_of_all_groups[i], '/','per_framefeatures_sum_allflies.csv'))
   }
  
  
  #orgenzieing the data 
  
  #only the third and first colom
  #the number 26997 is becuse some movie end with this frame
  degree_per_frames<-degree_csv[1:26997,c(1,3)]
  colnames(degree_per_frames)<-c("Frame","degree")
  #removing the last frames so the dataframe will be in the same size
  all_features_new<-all_features[1:26997,]
  colnames(all_features_new)<-str_remove(colnames(all_features_new), ".mat")
  if(without_ncloseflys){
    #removing nclose fly from corrleacton
      all_features_new <- all_features_new[,!grepl("nflies_close", colnames(all_features_new))]
  }

  
  
  #combining the degree to the df
  combined_degree_and_features<-cbind(all_features_new,degree_per_frames$degree)
  #calculate corrlaction 
  corrleaction=cor(combined_degree_and_features)
  df_corr<-as.data.frame(corrleaction)
  #want to get only the corrlaction of the degree
  degree_corr<-cbind(degree_corr,df_corr$`degree_per_frames$degree`)
  

}

#this part at the end,after making the all matrix
  #giving the name of the row to know what features are in the corrleaction
rownames(degree_corr)<-row.names(df_corr)
#just to not mess with the original
temp_degree_corr<-degree_corr


  #drop perfect correlations
  temp_degree_corr[temp_degree_corr == 1] <- NA 
  #turn into a 3-column table
  temp_degree_corr <- as.data.frame(as.table(temp_degree_corr))
  #remove the NA values from above 
  temp_degree_corr <- na.omit(temp_degree_corr) 
  #select significant values  
  temp_degree_corr <- subset(temp_degree_corr, abs(Freq) > 0.5) 
  #sort by highest correlation
  temp_degree_corr <-  temp_degree_corr[order(-abs(temp_degree_corr$Freq)),] 
  #print table
  print(temp_degree_corr)
  #turn corr back into matrix in order to plot with corrplot
  mtx_corr <- reshape2::acast(temp_degree_corr, Var1~Var2, value.var="Freq")
setwd(path_to_group)
if(without_ncloseflys){
  jpeg(filename = paste0(basename(path_to_group),"wo_nclose_corrleaction_degres_threshold05.jpeg"), width = 1200, height = 800)
corrplot(mtx_corr, is.corr=FALSE, tl.col="black", na.label=" ",tl.cex = 0.7)
dev.off()
}else{
  jpeg(filename = paste0(basename(path_to_group),"_corrleaction_degres_threshold05.jpeg"), width = 1200, height = 800)
corrplot(mtx_corr, is.corr=FALSE, tl.col="black", na.label=" ",tl.cex = 0.7)

dev.off()
}

}

```


```{r}

file_name_Save<-"C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/8.06/mycorrplot.png"

test<-read.csv("D:/allGroups/Females_Mated/Assa_Female_Mated_Unknown_RigA_20211025T132422/all_frames_degree.csv")


all_features<-read.csv("D:/allGroups/Females_Mated/Assa_Female_Mated_Unknown_RigA_20211025T132422/per_framefeatures_sum_allflies.csv")
sum_per_frames<-test[1:26997,c(1,3)]
colnames(sum_per_frames)<-c("Frame","degree")

library(stringr)



all_features_new<-all_features[1:26997,]


colnames(all_features_new)<-str_remove(colnames(all_features_new), ".mat")

data<-cbind(all_features_new,sum_per_frames$degree)


my_data <- data[, c(1,3,4,5,6,7)]

library("PerformanceAnalytics")


chart.Correlation(data, histogram=FALSE)

```




#tring things for corrleaction,didnt succesed but gave idea for network

```{r corrleaction}


file_name_Save<-"C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/8.06/mycorrplot.png"

test<-read.csv("D:/allGroups/Females_Mated/Assa_Female_Mated_Unknown_RigA_20211025T132422/all_frames_degree.csv")


all_features<-read.csv("D:/allGroups/Females_Mated/Assa_Female_Mated_Unknown_RigA_20211025T132422/per_framefeatures_sum_allflies.csv")
sum_per_frames<-test[1:26997,c(1,3)]
colnames(sum_per_frames)<-c("Frame","degree")

library(stringr)



all_features_new<-all_features[1:26997,]


colnames(all_features_new)<-str_remove(colnames(all_features_new), ".mat")

data<-cbind(all_features_new,sum_per_frames$degree)






# library
library(igraph)


# Make a correlation matrix:
mat=cor(data)
# Keep only high correlations
mat[mat<0.995]=0

# Make an Igraph object from this matrix:
network=graph_from_adjacency_matrix( mat, weighted=T, mode="undirected", diag=F)

plot(network)



data<-cbind(time=1:26997,data)

data<-ts(data)
ccf(data[,1],data[,2])

data_cor <- cor(data[ , colnames(data) != "degree"],  # Calculate correlations
                data$degree)
data_cor  

cor(data)
library(corrplot)
corrplot(data_cor, method="circle",tl.cex = 0.5)
corrplot(data_cor, type="upper", order="hclust", tl.col="black", tl.srt=45,tl.cex = 0.4)


png(filename = "C:/Users/barakli8/OneDrive - Bar Ilan University/Lital/weekly presentation/8.06/mycorrplot.png", width = 1200, height = 800)
corrplot(data_cor, method="circle", addCoef.col = 1, tl.cex = 0.5)
#dev.off()


#In this example, I’ll demonstrate how to get the Pearson correlation coefficient between a particular data frame variable with all the other variables in this data frame.



#In order to reduce the sheer quantity of variables (without having to manually pick and choose), Only variables above a specific significance level threshold are selected. It is set to 0.5 as the initial default.

library(dplyr)
corr_simple <- function(data=df,sig=0.5){
  #convert data to numeric in order to run correlations
  #convert to factor first to keep the integrity of the data - each value will become a number rather than turn into NA
  df_cor <- data %>% mutate_if(is.character, as.factor)
  df_cor <- df_cor %>% mutate_if(is.factor, as.numeric)
  #run a correlation and drop the insignificant ones
  
  #corr <- cor(df_cor[ , colnames(df_cor) != "degree"],  # Calculate correlations
  #             df_cor$degree) 
  
  corr<-cor(df_cor)
  #prepare to drop duplicates and correlations of 1     
  corr[lower.tri(corr,diag=TRUE)] <- NA 
  #drop perfect correlations
  corr[corr == 1] <- NA 
  #turn into a 3-column table
  corr <- as.data.frame(as.table(corr))
  #remove the NA values from above 
  corr <- na.omit(corr) 
  #select significant values  
  corr <- subset(corr, abs(Freq) > sig) 
  #sort by highest correlation
  corr <- corr[order(-abs(corr$Freq)),] 
  #print table
  print(corr)
  #turn corr back into matrix in order to plot with corrplot
  mtx_corr <- reshape2::acast(corr, Var1~Var2, value.var="Freq")
  
  #plot correlations visually
  png(filename = file_name_Save, width = 1200, height = 800)
  corrplot(mtx_corr, is.corr=FALSE, tl.col="black", na.label=" ",tl.cex = 0.55)
}
corr_simple(data)




res <- cor(data)


# Get some colors
col<- colorRampPalette(c("blue", "white", "red"))(80)
heatmap(x = res, col = col, symm = TRUE)




corr_mat <- round(cor(data),2) 
head(corr_mat)

# Install and load reshape2 package
library(reshape2)

# creating correlation matrix
corr_mat <- round(cor(data),2)

# reduce the size of correlation matrix
melted_corr_mat <- melt(corr_mat)
# head(melted_corr_mat)

# plotting the correlation heatmap
library(ggplot2)
ggplot(data = melted_corr_mat, aes(x=Var1, y=Var2,
                                   fill=value)) +
  geom_tile()

# Code to plot a reorederd heatmap

# Install and load reshape2 package
library(reshape2)

# creating correlation matrix
corr_mat <- round(cor(data),2)

# reorder corr matrix
# using corr coefficient as distance metric
dist <- as.dist((1-corr_mat)/2)

# hierarchical clustering the dist matrix
hc <- hclust(dist)
corr_mat <-corr_mat[hc$order, hc$order]

# reduce the size of correlation matrix
melted_corr_mat <- melt(corr_mat)
#head(melted_corr_mat)

#plotting the correlation heatmap
library(ggplot2)
ggplot(data = melted_corr_mat, aes(x=Var1, y=Var2, fill=value)) +
  geom_tile()



# Load and install heatmaply package
library(heatmaply)

# plotting corr heatmap
heatmaply_cor(x = cor(data), xlab = "Features",
              ylab = "Features", k_col = 2, k_row = 2)





```




