---
title: "degree"
output: html_document
---


##this script calculate at evry movie the avg degree for evey 60 frame(can be chnagable in numbers) and visulaize it 

```{r pressure, echo=FALSE}

library(openxlsx)
library(R.matlab)
path ="F:/allGroups/Females_Mated"
setwd(path)
  
dir<-list.dirs(recursive = F)
print(dir)
mat <- (readMat(paste0(dir[1], '/','Allinteraction.mat'))) # read each MAT file
sub_list_mat<-matrix(mat[["new.interactionFrameMatrix"]],nrow = 10, ncol = 10)
df_mat<-as.data.frame(sub_list_mat)


```


```{r}
f <- function(x) {
    if(is.list(x)) lapply(x, f)
    else ifelse(length(x) == 0, 0, x)
  }

  
  #REMOVE 0 (MEAN NO INTERACTION)
  for(i in 1:ncol(df_mat)){
    for(j in 1:nrow(df_mat)){
      if(length(unlist(df_mat[i,j])) == 0){
        df_mat[i,j] <- lapply(df_mat[i,j], function(x)x[lengths(x) == 0] <- 0)
      }
    }
  }
  
  df_mat<-na.omit(df_mat)

  

  #10 flys
  colnames(df_mat)<-c("1","2","3","4","5","6","7","8","9","10")
  rownames(df_mat)<-c("1","2","3","4","5","6","7","8","9","10")
  nodes<-c("1","2","3","4","5","6","7","8","9","10")
  nodes<-as.data.frame(nodes)
  all<-data.frame()
  
  number_of_flys<-10
  for(i in 1:number_of_flys){
    for(j in 1:number_of_flys){
      if(length(unlist(sub_list_mat[i,j]))!=0){
        temp_num_frames<-unlist(df_mat[i,j])
        tobind<-c(colnames(df_mat[i]),rownames(df_mat[j,]))
        tobind<-as.data.frame(t(tobind))
        
        seq_inter<- temp_num_frames[diff(temp_num_frames)>120]
        if(length(seq_inter)> 0){
          num_of_seq_iter<-length(seq_inter)
          current_iindex<-1
          for(k in 1:num_of_seq_iter){
            tobind<-c(colnames(df_mat[i]),rownames(df_mat[j,]))
            tobind<-as.data.frame(t(tobind))
            
            index<-which(temp_num_frames == seq_inter[k])
            tt_temp_num_frames<-as.data.frame(temp_num_frames)
            temp_all_inter<-tt_temp_num_frames[current_iindex:index,]
            current_iindex<-index+1
            tobind<-cbind(tobind,temp_all_inter[1])
            tobind<-cbind(tobind,temp_all_inter[length(temp_all_inter)])
            colnames(tobind)<-c("tail","head","onset","terminus")
            
            all<-rbind(all,tobind)
        }
        
        }else{
          tobind<-cbind(tobind,temp_num_frames[1])
          tobind<-cbind(tobind,temp_num_frames[length(temp_num_frames)])
          colnames(tobind)<-c("tail","head","onset","terminus")
          all<-rbind(all,tobind)
          
        }
        
      }
        
    }
  }
  
  colnames(all)<-c("tail","head","onset","terminus")
  
  all["head"] <- as.numeric(unlist(all["head"]))
  all["tail"] <- as.numeric(unlist(all["tail"]))
```

```{r}
#wanted to get all the rows in the spcific timeline


library(dplyr)
library(reshape2)
library(igraph)

value_avg_df<-data.frame()
#each 60 frames
numbers<-seq(1, 27001, by=60)
#for acast(need to read it documnation) so it will sum it as 1 
all<-cbind(all,1)

for(i in 1:(length(numbers)-1)){
  
  print(numbers[i])
  print(numbers[i+1])
  temp_between_values<-c()
  temp_between_values<-all %>% filter(numbers[i]>=onset & numbers[i+1] <=terminus)
  if( nrow(temp_between_values)!=0){
    #need to check if to remove this condition
  if(nrow(temp_between_values)<2){
  values<-acast(temp_between_values, tail~head,fun.aggregate=sum) 
  }else{
  values<-acast(temp_between_values, tail~head,fun.aggregate=sum) 
  }
  zero_matrix <- matrix(0, ncol = 10, nrow = 10)
  all_values<-acast(rbind(melt(values), melt(zero_matrix)), Var1~Var2, sum)
  net2 <- graph_from_adjacency_matrix(all_values,mode = "undirected")
  deg <- degree(net2, mode="all")
  value_avg_temp<-data.frame(begin=numbers[i],end=numbers[i+1],avg_value=mean(deg))
  value_avg_df<- bind_rows(value_avg_df,value_avg_temp)
  }else{
  value_avg_temp<-data.frame(begin=numbers[i],end=numbers[i+1],avg_value=0)
  value_avg_df<- bind_rows(value_avg_df,value_avg_temp)
  }
  }
  
#the else is to get the whole frame on interaction so we see the buildup
data<- as.data.frame(paste0(value_avg_df$begin,"-", value_avg_df$end))
data$value<-value_avg_df$avg_value
colnames(data)<-c("Frame","Value")


data$Frame <- as.character(data$Frame)
#Then turn it back into a factor with the levels in the correct order
data$Frame <- factor(data$Frame, levels=unique(data$Frame))

library(ggplot2)
ggplot(data = data, mapping = aes(x = Frame, y = Value))+    geom_bar(stat="identity", color="black", fill="gray")+theme(text = element_text(size=3),
        axis.text.x = element_text(angle=90, hjust=1)) 


#histogram of distrabution
with(value_avg_df, hist(avg_value))
library(stringr)

name_for_file<-paste0(basename(path),"_avg_degree.pdf")

ggsave(filename = name_for_file,device="pdf",path="C:/Users/lital/OneDrive - Bar Ilan University/Lital/weekly presentation/7.4")

```


debug for spcific frames
```{r}


library(dplyr)
all<-cbind(all,1)
temp_between_values<-all %>% filter(onset > 14201,terminus<14301)


library(reshape2)


if(nrow(temp_between_values)<2){
 values<-acast(temp_between_values, tail~head,fun.aggregate=sum) 
 values[1]<-1
}else{
  print("above 2 please check if its okay")
  values<-acast(temp_between_values, tail~head)

}


zero_matrix <- matrix(0, ncol = 10, nrow = 10)


library(reshape2)
all_values<-acast(rbind(melt(values), melt(zero_matrix)), Var1~Var2, sum)



library(igraph)
net2 <- graph_from_adjacency_matrix(all_values,mode = "undirected")
deg <- degree(net2, mode="all")
value_avg_df<-data.frame(begin=numbers[1],end=numbers[2],avg_value=mean(deg))
#doing the cumeltive thing,just need to put all the 1:10 flys and put in them 0 
```

