---
title: "Untitled"
output: html_document
date: '2022-07-17'
---









#moving avarge of component for multipul movies together for visual



```{r}
library(openxlsx)
library(stringr)
library(dplyr)
library(reshape2)
library(igraph)
library(R.matlab)
library(dplyr)
library(ggplot2)
library(zoo)
library(tidyr)




all_sd_and_avg_all_conditions_final<-NULL
main_path<-"D:/EX5_6"

list_of_all_groups<-list.dirs(path = main_path, full.names = TRUE, recursive = FALSE)

for (index_group in 1:length(list_of_all_groups)){
  path_to_group =list_of_all_groups[index_group]
  print(path_to_group)
  setwd(path_to_group)
  dir_subGroup<-list.dirs(recursive = F,path = path_to_group)
  for(num_of_movie in 1:length(dir_subGroup)){
      if(!file.exists(paste0(dir_subGroup[num_of_movie], '/','all_frames_degree_new.csv'))){
    warning(paste0("all_frames_degree.csv don't exist in ", dir_subGroup[num_of_movie]))
      }else{
    all_frames<-read.csv(paste0(dir_subGroup[num_of_movie],'/','all_frames_degree_new.csv'))
  }
  }


}
list_of_all_groups<-list.dirs(path = main_path, full.names = TRUE, recursive = FALSE)

for (index_group in 1:length(list_of_all_groups)){
  path_to_group =list_of_all_groups[index_group]
  print(path_to_group)
  setwd(path_to_group)
  dir_subGroup<-list.dirs(recursive = F,path = path_to_group)
  number_of_movies<-length(dir_subGroup)
  #find all files that have the file
  all.the.files <- dir(path_to_group, recursive=TRUE, pattern="^all_frames_degree_new.csv$" )
  #get the full path
all__subfile_fullpath<-paste0(path_to_group,"/",all.the.files)

library(purrr)
#bind all with coloms for current group
data_bined_csv<- 
    all__subfile_fullpath %>%  map_dfr( ~ read.csv(.x) )


data_colom_bined<- 
    all__subfile_fullpath %>%  map_dfc( ~ read.csv(.x) )

#keep only the values,I didnt worte the movie name cuz he was very long and distrupted the visullization of the graph
#actuall changed my mind,did rbind and only removed the frames so i could show each group together


value_of_density <- data_colom_bined[,grepl("Value", colnames(data_colom_bined))]


#gave evrey movie a number
colnames(value_of_density)<-1:length(all.the.files)


colnames(value_of_density)<-paste0("value",colnames(value_of_density))



all_movie_component<-value_of_density



###each colum individaully rollmean
rollmeans_colums<-NULL
for(colums in 1:number_of_movies){
  #doing rollmean on each colum separately with batch of 1000 in each rollmean
  #added pad of na at the ends
  means <- sapply(c("center"),
                function(x)zoo::rollmean(all_movie_component[,colums],1000,align = x, na.pad = TRUE))
  #combind the colums together
  rollmeans_colums<-cbind(rollmeans_colums,means)
}
####


###final formating of the data for visual for the meanroll
rollmeans_colums<-as.data.frame(rollmeans_colums)
#remove na that was for padding
means_no_na<-rollmeans_colums %>% drop_na()
#add the frames
means_no_na$frame<-1:nrow(means_no_na)
#names of coloms
colnames(means_no_na)<-c(c(1:number_of_movies),"frame")
#melt the data for visual
melted_means_no_na<- melt(data = means_no_na, id.vars = "frame")
###


### formating for the original compnent size for comprence
all_movie_component$frame<-1:nrow(all_movie_component)
colnames(all_movie_component)<-c(c(1:number_of_movies),"frame")
melted_original_comp<- melt(data = all_movie_component, id.vars = "frame")
###


###ploting
#moving avg
movingavg_all_movie<-ggplot(melted_means_no_na, aes(frame,value,colour = variable)) + 
  geom_line(size=1) +
  facet_wrap(~variable) +ylab("density")+ ggtitle(paste0(basename(path_to_group)," density moving avarge "))

#original
original_comp_all_movie<-ggplot(melted_original_comp, aes(frame,value,colour = variable)) + 
  geom_line(size=1) +
  facet_wrap(~variable)+ylab("component size")+ ggtitle(paste0(basename(path_to_group)," density  original"))

geom_line(size=1)
#moving avg all movies on top each over with midean

movingavg_together<-ggplot(melted_means_no_na, aes(frame,value,colour = variable)) + 
  geom_line(size=1) +   stat_summary(fun = "median", geom = "line", color = "black", size = 1.1)+ylab("density")+ ggtitle(paste0(basename(path_to_group)," density  moving avarge"))



###

png(file = paste0(path_to_group,"/moving_all_movies_density.png"))
plot(movingavg_all_movie)
dev.off()
png(file = paste0(path_to_group,"/original_all_movie_density.png"))
plot(original_comp_all_movie)
dev.off()

}



```



```{r}
library(openxlsx)
library(stringr)
library(dplyr)
library(reshape2)
library(igraph)
library(R.matlab)
library(dplyr)
library(ggplot2)
library(zoo)
library(tidyr)




all_condtion_se_and_mean<-NULL
for_statistic<-NULL
main_path<-"D:/EX5_6"

list_of_all_groups<-list.dirs(path = main_path, full.names = TRUE, recursive = FALSE)

for (index_group in 1:length(list_of_all_groups)){
  path_to_group =list_of_all_groups[index_group]
  print(path_to_group)
  setwd(path_to_group)
  dir_subGroup<-list.dirs(recursive = F,path = path_to_group)
  for(num_of_movie in 1:length(dir_subGroup)){
      if(!file.exists(paste0(dir_subGroup[num_of_movie], '/','all_frames_degree_new.csv'))){
    warning(paste0("all_frames_degree.csv don't exist in ", dir_subGroup[num_of_movie]))
      }else{
    all_frames<-read.csv(paste0(dir_subGroup[num_of_movie],'/','all_frames_degree_new.csv'))
  }
  }


}
list_of_all_groups<-list.dirs(path = main_path, full.names = TRUE, recursive = FALSE)

for (index_group in 1:length(list_of_all_groups)){
  path_to_group =list_of_all_groups[index_group]
  print(path_to_group)
  setwd(path_to_group)
  dir_subGroup<-list.dirs(recursive = F,path = path_to_group)
  number_of_movies<-length(dir_subGroup)
  #find all files that have the file
  all.the.files <- dir(path_to_group, recursive=TRUE, pattern="^all_frames_degree_new.csv$" )
  #get the full path
all__subfile_fullpath<-paste0(path_to_group,"/",all.the.files)

library(purrr)
#bind all with coloms for current group
data_bined_csv<- 
    all__subfile_fullpath %>%  map_dfr( ~ read.csv(.x) )


data_colom_bined<- 
    all__subfile_fullpath %>%  map_dfc( ~ read.csv(.x) )

#keep only the values,I didnt worte the movie name cuz he was very long and distrupted the visullization of the graph
#actuall changed my mind,did rbind and only removed the frames so i could show each group together


value_of_density <- data_colom_bined[,grepl("Value", colnames(data_colom_bined))]


#gave evrey movie a number
colnames(value_of_density)<-1:length(all.the.files)


colnames(value_of_density)<-paste0("value",colnames(value_of_density))



all_movie_component<-value_of_density



###each colum individaully rollmean
rollmeans_colums<-NULL
for(colums in 1:number_of_movies){
  #doing rollmean on each colum separately with batch of 1000 in each rollmean
  #added pad of na at the ends
  means <- sapply(c("center"),
                function(x)zoo::rollmean(all_movie_component[,colums],1000,align = x, na.pad = TRUE))
  #combind the colums together
  rollmeans_colums<-cbind(rollmeans_colums,means)
}
####


###final formating of the data for visual for the meanroll
rollmeans_colums<-as.data.frame(rollmeans_colums)
#remove na that was for padding
means_no_na<-rollmeans_colums %>% drop_na()
#add the frames
#names of coloms
colnames(means_no_na)<-c(c(1:number_of_movies))
#melt the data for visual

library("plotrix")


for_statistic<-cbind(for_statistic,(t(means_no_na[nrow(means_no_na),])))

Mean= rowMeans(means_no_na)


se=rowSds(as.matrix(means_no_na))/sqrt(length(means_no_na))
mean_and_se_per_conditions<-as.data.frame(cbind(Mean,se))
mean_and_se_per_conditions$frame<-1:nrow(mean_and_se_per_conditions)
mean_and_se_per_conditions$group<-basename(path_to_group)



all_condtion_se_and_mean<-bind_rows(all_condtion_se_and_mean,mean_and_se_per_conditions)

colnames(for_statistic)[index_group]<-basename(path_to_group)



}
for_statistic<-as.data.frame(for_statistic)
melt_data <- melt(for_statistic) 
for_statistic$num_of_movie<-1:18
for_statistic$num_of_movie <- factor(for_statistic$num_of_movie)

aov1 <- aov(Females_Mated ~Females_Grouped+Females_Singles+Males_Mated+Males_Grouped+Males_Singles , data=for_statistic)
summary(aov1)
TukeyHSD(aov1)


component_plot_facet <- ggplot(data=all_condtion_se_and_mean, aes(y=Mean, x=frame, group=group, colour=group,
                      fill=group)) +scale_colour_manual(values = c("Females_Mated"="red", "Females_Grouped"="darkmagenta", "Females_Singles"="deeppink1", "Males_Grouped"="orange","Males_Mated"="dodgerblue3","Males_Singles"="chartreuse4")) +
geom_point(size=0.5) +
geom_line(size=0.5) +
geom_ribbon(aes(ymin=Mean-se, ymax=Mean+se), alpha=0.15, linetype=0) +scale_fill_manual(values = c("Females_Mated"="red", "Females_Grouped"="darkmagenta", "Females_Singles"="deeppink1", "Males_Grouped"="orange","Males_Mated"="dodgerblue3","Males_Singles"="chartreuse4")) +facet_wrap(~ group)+
theme_classic()+ggtitle("density (after moving avarge) per frame per conditions all movies with se") +
  xlab("frames") + ylab("density") +theme(
plot.title = element_text(color="black", size=12, face="bold.italic"),
axis.title.x = element_text(color="black", size=10, face="bold"),
axis.title.y = element_text(color="black", size=10, face="bold"))

plot(component_plot_facet)

# looks ok, no lines at the edges

component_plot <- ggplot(data=all_condtion_se_and_mean, aes(y=Mean, x=frame, group=group, colour=group,
                      fill=group)) +scale_colour_manual(values = c("Females_Mated"="red", "Females_Grouped"="darkmagenta", "Females_Singles"="deeppink1", "Males_Grouped"="orange","Males_Mated"="dodgerblue3","Males_Singles"="chartreuse4")) +
geom_point(size=0.5) +
geom_line(size=0.5) +
geom_ribbon(aes(ymin=Mean-se, ymax=Mean+se), alpha=0.15, linetype=0) +scale_fill_manual(values = c("Females_Mated"="red", "Females_Grouped"="darkmagenta", "Females_Singles"="deeppink1", "Males_Grouped"="orange","Males_Mated"="dodgerblue3","Males_Singles"="chartreuse4")) +
theme_classic()+ggtitle("density (after moving avarge) per frame all conditions all movies with se") +
  xlab("frames") + ylab("density") +theme(
plot.title = element_text(color="black", size=13, face="bold.italic"),
axis.title.x = element_text(color="black", size=13, face="bold"),
axis.title.y = element_text(color="black", size=13, face="bold"))
# looks ok, no lines at the edges


plot(component_plot)

```
