---
title: "Untitled"
author: "lital barak"
date: "2022-08-14"
output: html_document
---


avarge of density of all condition all movies with error bars
```{r}

all_sd_and_avg_all_conditions_final<-NULL
main_path<-"D:/allGroups"

list_of_all_groups<-list.dirs(path = main_path, full.names = TRUE, recursive = FALSE)

for (index_group in 1:length(list_of_all_groups)){
  path_to_group =list_of_all_groups[index_group]
  print(path_to_group)
  setwd(path_to_group)
  dir_subGroup<-list.dirs(recursive = F,path = path_to_group)
  for(num_of_movie in 1:length(dir_subGroup)){
      if(!file.exists(paste0(dir_subGroup[num_of_movie], '/','all_frames_degree_new.csv'))){
    warning(paste0("all_frames_degree.csv don't exist in ", dir_subGroup[num_of_movie]))
      }else{
    all_frames<-read.csv(paste0(dir_subGroup[num_of_movie],'/','all_frames_degree_new.csv'))
  }
  }


}
list_of_all_groups<-list.dirs(path = main_path, full.names = TRUE, recursive = FALSE)

for (index_group in 1:length(list_of_all_groups)){
  path_to_group =list_of_all_groups[index_group]
  print(path_to_group)
  setwd(path_to_group)
  dir_subGroup<-list.dirs(recursive = F,path = path_to_group)
  
  #find all files that have the file
  all.the.files <- dir(path_to_group, recursive=TRUE, pattern="^all_frames_degree_new.csv$" )
  #get the full path
all__subfile_fullpath<-paste0(path_to_group,"/",all.the.files)

library(purrr)
#bind all with coloms for current group
data_bined_csv<- 
    all__subfile_fullpath %>%  map_dfr( ~ read.csv(.x) )


data_colom_bined<- 
    all__subfile_fullpath %>%  map_dfc( ~ read.csv(.x) )

#keep only the values,I didnt worte the movie name cuz he was very long and distrupted the visullization of the graph
#actuall changed my mind,did rbind and only removed the frames so i could show each group together


value_of_density <- data_colom_bined[,grepl("Value", colnames(data_colom_bined))]


#gave evrey movie a number
colnames(value_of_density)<-1:length(all.the.files)


colnames(value_of_density)<-paste0("value",colnames(value_of_density))




library(dplyr)
library(matrixStats)

columns <- c(colnames(value_of_density))

#value_of_density<-value_of_density %>% 
#mutate(Mean= rowMeans(.[columns]), stdev=rowSds(as.matrix(.[columns])))

Mean= rowMeans(value_of_density)
se=rowSds(as.matrix(value_of_density))/sqrt(length(value_of_density))
mean_and_sd_all_conditions<-as.data.frame(cbind(Mean,se))
mean_and_sd_all_conditions$frame<-1:nrow(mean_and_sd_all_conditions)
mean_and_sd_all_conditions$group<-basename(path_to_group)


all_sd_and_avg_all_conditions_final<-bind_rows(all_sd_and_avg_all_conditions_final,mean_and_sd_all_conditions)
#ggplot(mean_and_sd_all_conditions, aes(frame,Mean,color="blue")) +  geom_point(size=0.5)+
#geom_ribbon(aes(ymin=Mean-stdev, ymax=Mean+stdev),alpha = .2)

}

pl <- ggplot(data=all_sd_and_avg_all_conditions_final, aes(y=Mean, x=frame, group=group, colour=group,
                      fill=group)) +
geom_point() +
geom_line() +
geom_ribbon(aes(ymin=Mean-se, ymax=Mean+se), alpha=0.3, linetype=0) +facet_wrap(~ group)+
theme_minimal()+ggtitle("density per frame all conditions all movies with se") +
  xlab("frames") + ylab("density") +theme(
plot.title = element_text(color="black", size=12, face="bold.italic"),
axis.title.x = element_text(color="black", size=10, face="bold"),
axis.title.y = element_text(color="black", size=10, face="bold"))

# looks ok, no lines at the edges
plot(pl)

```



```{r}



library(plotly)

set.seed(1)
dt <- data.frame(x=rep(1:7,2), group=rep(letters[1:2], each=7), value=runif(14))
dt$lwr <- dt$value*.9
dt$upr <- dt$value*1.1

# build plot in ggplot, don't want lines at the edge
pl <- ggplot(data=dt, aes(y=value, x=x, group=group, colour=group,
                      fill=group)) +
geom_point() +
geom_line() +
geom_ribbon(aes(ymin=lwr, ymax=upr), alpha=.3, linetype=0) +
theme_minimal()

# looks ok, no lines at the edges
pl

# no lines at edges
dd = ggplotly(pl)
dd$x$data[[3]]$line$color = "rgba(248,118,109,0.0)"
dd$x$data[[4]]$line$color = "rgba(0,191,196,0.0)"
dd
```

