---
title: "linear_regression_velmagVSdegree"
output: html_document
date: '2022-05-31'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

linear regrrsion single movie train and test


```{r}
#install.packages('olsrr')
scaled<-TRUE

all_other_features<-read.csv("D:/Elia/cyp6a20/WT_With_Cyp6a20/Assa_Females_Obp69a_GFP_Unknown_RigA_20220617T100935/per_framefeatures_sum_allflies.csv")[1:26997,]

degree_csv<-read.csv("D:/Elia/cyp6a20/WT_With_Cyp6a20/Assa_Females_Obp69a_GFP_Unknown_RigA_20220617T100935/all_frames_degree_new.csv")


  degree_csv<-degree_csv[1:26997,c(1,3)]
  colnames(degree_csv)<-c("Frame","degree")
  degree<-degree_csv$degree
  combined_degree_and_features<-cbind(all_other_features,degree)

  if(scaled == TRUE){
    data_scaled<-as.data.frame(scale(combined_degree_and_features))
    lm_sclaed<-lm(degree ~ .,data =data_scaled)
    summary(lm_sclaed)
    predi<-as.data.frame(predict(lm_sclaed))
      
      

  }else{
    non_scaledcombined_degree_and_features<-combined_degree_and_features
    data_non_scaled<-non_scaledcombined_degree_and_features
    
    lm_non_scaled<-lm(degree ~ .,data =data_non_scaled)
    summary(lm_non_scaled)
    predi<-as.data.frame(predict(lm_non_scaled))
      
      
  }
  


#nonscaled
    #scaled_combined<-scale(combined_degree_and_features[,-ncol(combined_degree_and_features)])
    #scalign on all features works better with the degree
    #combined_degree_and_features<-scale(combined_degree_and_features)
    #data_scaled<-as.data.frame(combined_degree_and_features)
  
    
    
    
 #   d <- data.frame(
  #x=runif(100),
  #y=rnorm(100)
#)

#d <- within(d, s.x <- scale(x))
    
 #m1 <- lm(y~s.x, data=d)
  
# attributes(combined_degree_and_features)
    #lm to nflies close
    
    

   #  lm_fliesn<-lm(degree ~  dnose2ell.mat,data =data_non_scaled)

  #summary(lm_fliesn)
   #   predi_n_close<-as.data.frame(predict(lm_fliesn))

      
      
      

      

    #lm on all data

      
      
      
      
      
      
      
      
      #visualaztion of the diffrnece between prdiction and reality on the same dataset
      
      
library(dplyr)
library(tidyr)
library(ggplot2)
if(scaled == TRUE){
  a=predi$`predict(lm_sclaed)`
b=scale(degree)
time=degree_csv$Frame

df_ploting_prediction<-data.frame(predict=a,degree=b,time=time)

library(reshape2)
df_ploting_prediction <- melt(df_ploting_prediction, id.vars = 'time')



library(ggplot2)
ggplot(df_ploting_prediction, aes(x =time , y = value, color = variable)) + geom_line()



}





#doing test and train,it was the train,now its the test

all_other_features_test<-read.csv("D:/Elia/cyp6a20/WT_With_Cyp6a20/Assa_Females_Obp69a_GFP_Unknown_RigA_20220617T102949/per_framefeatures_sum_allflies.csv")[1:26997,]

degree_csv_test<-read.csv("D:/Elia/cyp6a20/WT_With_Cyp6a20/Assa_Females_Obp69a_GFP_Unknown_RigA_20220617T102949/all_frames_degree_new.csv")


  degree_csv_test<-degree_csv_test[1:26997,c(1,3)]
  colnames(degree_csv_test)<-c("Frame","degree")
  degree<-degree_csv_test$degree
  
  combined_degree_and_features_test<-cbind(all_other_features_test,degree)

#scaled_test<-scale(combined_degree_and_features_test)


#scaled

if(scaled == TRUE){
  data_scaled_only_features_test<-as.data.frame(scale(all_other_features_test))
    degree<-scale(degree)
  data_scaled_only_features_test$predicted.y <- predict.lm(lm_sclaed, newdata=data_scaled_only_features_test)
    data_scaled_only_features_test<-cbind(data_scaled_only_features_test,degree)
    
    test_prediaction<-data_scaled_only_features_test
    
}else{
  data_non_scaled_only_features_test<-all_other_features_test
    data_non_scaled_only_features_test$predicted.y <- predict.lm(lm_non_scaled, newdata=data_non_scaled_only_features_test)
    data_non_scaled_only_features_test<-cbind(data_non_scaled_only_features_test,degree)
    test_prediaction<-data_non_scaled_only_features_test


}

    #nonscaled


    
    
library(dplyr)
library(tidyr)
library(ggplot2)
a=test_prediaction$predicted.y
b=degree
time=degree_csv_test$Frame

together_test<-data.frame(predict=a,degree=b,time=time)

library(reshape2)
together_test <- melt(together_test, id.vars = 'time')

#DF <- data.frame(time = seq(as.Date("1999-06-15"),as.Date("2008-06-15"), by= "years"),
   #              a = c(22.3,24.1,35,35,35.9,39.2,34.8,31.5,29.1,25.8),
  #               b = c(22,24.9,31,34,37.5,36.3,32.1,29.7,28.6,23.9))

library(ggplot2)
ggplot(together_test, aes(x =time , y = value, color = variable)) + geom_line()


#data_frame(time, a, b) %>%
#  mutate(diff_a_b =(a - b)) %>% 
 # gather(key, value, a, b) %>% 
 # ggplot(., aes(time)) +
  #geom_line(aes(y = value, color = key)) + 
  #geom_col(aes(y = diff_a_b, fill = key))
     # s.x<-predi$`predict(lm1)`
#s.x * attr(s.x, 'scaled:scale') + attr(s.x, 'scaled:center')

   # data_cor <- cor(combined_cc_and_features[ , colnames(combined_cc_and_features) != 
    #"cc_frame_and_value$cc"],  # Calculate correlations
   #             combined_cc_and_features$`cc_frame_and_value$cc`)
    
    #removed what was with na and non sig
   # lm1<-lm(cc ~ . -theta_mm.mat -timestamps.mat -y_mm.mat -x_mm.mat -dt.mat -dist2wall.mat -a_mm.mat -b_mm.mat -a.mat -absdtheta.mat -absdv_cor.mat -corfrac_min.mat -yaw.mat -veltoward_nose2ell.mat -velmag_nose.mat -velmag.mat -signdtheta.mat -phi.mat -dv_cor.mat -du_tail.mat -dphi.mat -flipdv_cor.mat -dangle2wall.mat -absphidiff_anglesub.mat, data=combined_cc_and_features)
    
    
     # lm1<-lm(cc ~ y_mm.mat+y.mat+ynose_mm.mat
#+angle2wall.mat+theta.mat+theta_mm.mat+anglesub.mat+dist2wall.mat ,data=combined_cc_and_features)  
  #summary(lm1)
  
  
  #predi<-as.data.frame(predict(lm1))
  
  
  
  
  ##WILL NEVER WORK,TOO MUCH VARIBLES
  #NEED TO TRY MYSELF WITH CORRLACTION?
  #or with comon sense and choose 10 varibles top
library(leaps)
  
  Best_Subset <-
    regsubsets(cc~.,
               data =combined_cc_and_features,
               nbest = 1,      # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive",really.big=T)
summary_best_subset <- summary(regsubsets.out)
as.data.frame(summary_best_subset$outmat)
```


#THAT WAS THE TRAIN OF THE MODLE,NOW IT IS THE TEST FOR PREDICTION


```{r}

```
#will creat avarge of all the varibles in all the frames and than will check in each movie invidually for the predicition

```{r}


#creat avarge of all movie in female mated ,creat linear regression and predict

#get the avarge of all the degrees
all.the.files <- dir("D:\\allGroups\\Females_Mated", recursive=TRUE, pattern="^all_frames_degree.csv$" )

all.the.files<-paste0("D:\\allGroups\\Females_Mated","\\",all.the.files)
library(purrr)
#bind all with coloms
all.the.data <- 
    all.the.files %>%  map_dfc( ~ read.csv(.x) )

#combined by coloms

wo_framenum <- all.the.data[,!grepl("Frame", colnames(all.the.data))]

wo_frame_and_num <- wo_framenum[,!grepl("X", colnames(wo_framenum))]

wo_frame_and_num_group <- wo_frame_and_num[,!grepl("group", colnames(wo_frame_and_num))]

colnames(wo_frame_and_num_group)<-1:19

mean_everyrow<-as.data.frame(rowMeans(wo_frame_and_num_group, na.rm = FALSE, dims = 1))

mean_everyrow<-cbind(1:27000,mean_everyrow)
colnames(mean_everyrow)<-c("Frame","Value")




all.the.files_all_featurs <- dir("D:\\allGroups\\Females_Mated", recursive=TRUE, pattern="^per_framefeatures_sum_allflies.csv$" )

all.the.files_all_featurs<-paste0("D:\\allGroups\\Females_Mated","\\",all.the.files_all_featurs)

for(i in 1:19){
  
  temp<-read.csv(all.the.files_all_featurs)
  
}

#to see what is the limit of combining the data frame
test_file_names<-all.the.files_all_featurs[1:3]

df <-all.the.files_all_featurs  %>% 
  lapply(read.csv) %>% 
  bind_rows 

library(purrr)
#bind all with coloms
all.the.data_all_features <- 
    test_file_names %>%  map_dfc( ~ read.csv(.x) )







```



```{r}

library(openxlsx)
library(stringr)
library(dplyr)
library(reshape2)
library(igraph)
library(R.matlab)
path ="D:/allGroups/Females_Mated"
setwd(path)
number_of_flys<-10
number_of_frame<-1
facade<-FALSE

#seq by the  number of frames
numbers<-seq(1, 27001, by=number_of_frame)

f <- function(x) {
    if(is.list(x)) lapply(x, f)
    else ifelse(length(x) == 0, 0, x)
}



dir<-list.dirs(recursive = F,path = path)

num_of_movie=1


velmag<-read.csv(paste0(dir[num_of_movie],"/","perframe_sum_allflies.csv"))
degree<-read.csv(paste0(dir[num_of_movie],"/","all_frames_degree.csv"))["Value"]
degree<-rbind(degree,0)

#velmag<-scale(velmag, center = TRUE, scale = TRUE)

#degree<-scale(degree, center = TRUE, scale = TRUE)

combined_velmage_degree<-cbind(velmag,degree)



combined_velmage_degree %>%
  as.data.frame() %>%
  GGally::ggpairs()


library(ggplot2)
combined_velmage_degree %>%
  as.data.frame() %>%
  ggplot(aes(x=Velmag_Sum, y=Value)) +
    ylab("sum of velmage per frame all flies ") +
    xlab("the degree in each frame of all flies") +
    geom_point()+ 
    geom_smooth(method="lm", se=FALSE)

simple.fit<-lm(formula =Velmag_Sum ~ Value, data=combined_velmage_degree)
summary(simple.fit)
plot(simple.fit)
```

