# -*- coding: utf-8 -*-
"""For Lital.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Rqyk2SVgSMIfRHjmRF0knYok0eTXaes
"""

#all the imports
import json
import pandas as pd
from scipy import stats
import seaborn as sns
import matplotlib.pyplot as plt

#read path and filenames from json
with open('private.json', 'r') as fp:
    data = json.load(fp)
    
#
path = data["path"]
clean_csv = data["clean-csv"]

#read the clean data
flies = pd.read_csv(path + clean_csv, index_col = 0)

#flies.shape
flies.head()

#z-score to all but "conditioning"
behaviors_feature_names = flies.columns.to_list() 
behaviors_feature_names.remove('conditioning')

for i in behaviors_feature_names:
  flies[i] = stats.zscore(flies[i])

conditionings = flies["conditioning"].unique().tolist()
scores = {"Aggregation", "Chain", "Chase", "Grooming", "Interaction", "Song", "Stop", "Touch", "Turn", "Walk"}
tracking = set(behaviors_feature_names) - scores
scores = list(scores)
tracking = list(tracking)

flies.drop(tracking, axis = 1, inplace = True)

flies[scores].hist(bins = 50, figsize = (30, 20), layout = (5, 2));

#Walk, Grooming, Stop, Turn appears to be somewhat normal
#Chase, Aggresion, Touch, Song, Chain, Interaction appears to be somewhat poisson

fig, ax = plt.subplots(5, 2, figsize = (20, 20))
for score, subplot in zip(scores, ax.flatten()):
    sns.boxplot(x = 'conditioning', y = score, data = flies, ax = subplot)
    
#Chase distribution is highly unusual and one sided
#Aggresion, Touch, Song, Interaction, Chain are unusual
#Walk, Grooming, Stop, Turn seems normal

#pairing plot of all the scoring
sns.pairplot(flies, hue = 'conditioning')

# correlation between Walk, Stop, Grooming & Turn

#Deceiding on which features and behaviors we want to focus on - the decision was derived from the EDA and the article insights

chosen = {"conditioning", "Grooming", "Chain", "Chase", "velmag", "dcenter", "anglesub", "nflies_close"}
chosen_flies = flies[chosen]

chosen_flies.to_csv(path + chosen_csv)