setwd('F:/scripts_for_adding_netwrok/scatter_plot')
source("averages per movie by file.R")
setwd('F:/scripts_for_adding_netwrok/scatter_plot')
source("import classifier files and calculate per frame.R")
setwd('F:/scripts_for_adding_netwrok/scatter_plot')
source("creatNetwork3popforscatter.R")
setwd('F:/scripts_for_adding_netwrok/scatter_plot')
source("bout length and frequency for classifiers.R")
setwd('F:/scripts_for_adding_netwrok/scatter_plot')
source("combine kinetic and classifiers to signature.R")